version: '3'
services:
  web:
    image: server
    container_name: web
    command: bash -c "gunicorn community.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
    networks:
      - server

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - server

networks:
  server: