# Generated by Django 5.0.6 on 2024-07-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='nickname',
        ),
    ]
