# Generated by Django 5.0.6 on 2024-07-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_user_board_nickname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='nickname',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='nickname',
            new_name='user',
        ),
    ]
